---
Resources:
  SimpleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t3.micro
      ImageId: ami-01816d07b1128cd2d  
      Tags:
        - Key: Name
          Value: apponix-cloudformation
